-- Biblioteca inicial de ejercicios, cargada desde la planilla del profe
-- (agrupados por músculo principal). Se puede correr una sola vez; si se
-- corre de nuevo no duplica (se fija por nombre).
insert into public.ejercicios (nombre, grupo_muscular)
select * from (values
  ('Press banca plano con barra', 'Pectorales'),
  ('Press banca inclinado con barra', 'Pectorales'),
  ('Press banca declinado con barra', 'Pectorales'),
  ('Press banca plano con mancuernas', 'Pectorales'),
  ('Press inclinado con mancuernas', 'Pectorales'),
  ('Press en máquina convergente', 'Pectorales'),
  ('Press horizontal en máquina', 'Pectorales'),
  ('Fondos en paralelas inclinados', 'Pectorales'),
  ('Flexiones de brazos', 'Pectorales'),
  ('Flexiones con pies elevados', 'Pectorales'),
  ('Aperturas con mancuernas', 'Pectorales'),
  ('Cruce de poleas', 'Pectorales'),
  ('Pec deck', 'Pectorales'),
  ('Press militar con barra', 'Hombros'),
  ('Press de hombros con mancuernas', 'Hombros'),
  ('Press de hombros en máquina', 'Hombros'),
  ('Press Arnold', 'Hombros'),
  ('Press unilateral en polea', 'Hombros'),
  ('Pike push-up', 'Hombros'),
  ('Dominadas pronas', 'Espalda'),
  ('Dominadas supinas', 'Espalda'),
  ('Dominadas neutras', 'Espalda'),
  ('Jalón al pecho agarre pronado', 'Espalda'),
  ('Jalón al pecho agarre neutro', 'Espalda'),
  ('Jalón unilateral en polea', 'Espalda'),
  ('Pullover en polea', 'Espalda'),
  ('Remo con barra', 'Espalda'),
  ('Remo Pendlay', 'Espalda'),
  ('Remo con mancuerna', 'Espalda'),
  ('Remo en máquina con pecho apoyado', 'Espalda'),
  ('Remo sentado en polea', 'Espalda'),
  ('Remo unilateral en polea', 'Espalda'),
  ('Face pull', 'Hombros'),
  ('Pájaro con mancuernas', 'Hombros'),
  ('Reverse pec deck', 'Hombros'),
  ('Sentadilla trasera', 'Piernas'),
  ('Sentadilla frontal', 'Piernas'),
  ('Hack squat', 'Piernas'),
  ('Prensa de piernas', 'Piernas'),
  ('Sentadilla búlgara', 'Piernas'),
  ('Zancadas', 'Piernas'),
  ('Step-up', 'Piernas'),
  ('Extensión de rodilla', 'Piernas'),
  ('Peso muerto convencional', 'Piernas'),
  ('Peso muerto rumano', 'Piernas'),
  ('Peso muerto rumano con mancuernas', 'Piernas'),
  ('Hip thrust con barra', 'Glúteos'),
  ('Hip thrust en máquina', 'Glúteos'),
  ('Pull-through en polea', 'Glúteos'),
  ('Extensión lumbar 45°', 'Espalda'),
  ('Curl femoral tumbado', 'Piernas'),
  ('Curl femoral sentado', 'Piernas'),
  ('Curl femoral unilateral', 'Piernas'),
  ('Nordic hamstring curl', 'Piernas'),
  ('Abducción de cadera en máquina', 'Glúteos'),
  ('Aducción de cadera en máquina', 'Piernas'),
  ('Patada de glúteo en polea', 'Glúteos'),
  ('Elevación de talones de pie', 'Piernas'),
  ('Elevación de talones sentado', 'Piernas'),
  ('Elevación de talones en prensa', 'Piernas'),
  ('Curl con barra', 'Bíceps'),
  ('Curl con mancuernas', 'Bíceps'),
  ('Curl inclinado con mancuernas', 'Bíceps'),
  ('Curl predicador', 'Bíceps'),
  ('Curl martillo', 'Bíceps'),
  ('Curl en polea baja', 'Bíceps'),
  ('Press cerrado', 'Tríceps'),
  ('Fondos para tríceps', 'Tríceps'),
  ('Extensión de tríceps en polea', 'Tríceps'),
  ('Extensión de tríceps por encima de la cabeza', 'Tríceps'),
  ('Press francés', 'Tríceps'),
  ('Elevación lateral con mancuernas', 'Hombros'),
  ('Elevación lateral en polea', 'Hombros'),
  ('Elevación lateral en máquina', 'Hombros'),
  ('Elevación frontal', 'Hombros'),
  ('Crunch en polea', 'Abdominales'),
  ('Crunch en máquina', 'Abdominales'),
  ('Elevación de piernas colgado', 'Abdominales'),
  ('Rueda abdominal', 'Abdominales'),
  ('Plancha', 'Abdominales'),
  ('Pallof press', 'Abdominales'),
  ('Encogimientos con barra', 'Espalda'),
  ('Encogimientos con mancuernas', 'Espalda'),
  ('Curl de muñeca', 'Antebrazo'),
  ('Extensión de muñeca', 'Antebrazo')
) as datos(nombre, grupo_muscular)
where not exists (
  select 1 from public.ejercicios e where e.nombre = datos.nombre
);
