-- 023 · Biblioteca con GIF: 750 ejercicios de FitCron
-- ----------------------------------------------------------------------
-- Carga la lista de FitCron (planilla FitCron_750.xlsx) en la biblioteca,
-- cada uno con su GIF animado. Los GIF viven dentro de la app
-- (public/ejercicios/fitcron-N.webp, con su versión chica en
-- public/ejercicios/mini), así que "imagen_url" guarda una dirección
-- corta como '/ejercicios/fitcron-12.webp'.
--
-- Qué hace:
--   1) Suma a "ejercicios" la columna "origen" (de dónde vino el
--      ejercicio, por ejemplo 'fitcron-12'). Sirve para no duplicar nada si
--      este archivo se corre de nuevo, aunque el profe haya cambiado el
--      nombre de alguno.
--   2) Si ya había un ejercicio con el mismo nombre (sin importar
--      mayúsculas), no crea otro: le pone el GIF (solo si no tenía foto).
--   3) Crea los que faltan, con su grupo muscular y sus categorías.
--   4) A los ejercicios que ya estaban cargados de antes (SQL 004) y tienen
--      un equivalente claro en FitCron les pone ese GIF, solo si todavía no
--      tenían foto (por ejemplo "Sentadilla trasera" ← "Sentadilla con
--      Barra"). No cambia nombres, categorías ni rutinas.
--   5) Muestra un resumen: tienen que ser 750 de FitCron.
--
-- Cambios de nombre respecto a la planilla (para que no haya dos iguales):
-- los 8 de cuello llevan "(cuello)" y los 7 nombres que FitCron repite en
-- dos grupos llevan el grupo entre paréntesis (por ejemplo "Fondos en
-- Máquina (tríceps)" y "Fondos en Máquina (pecho)").
--
-- No borra nada. Se puede correr más de una vez sin romper nada.

-- 1) Columna "origen" -------------------------------------------------------
alter table public.ejercicios add column if not exists origen text;
create unique index if not exists ejercicios_origen_unico on public.ejercicios (origen);

-- Lista de FitCron (tabla temporal: desaparece sola al terminar) -----------
drop table if exists pg_temp.carga_fitcron;
create temporary table carga_fitcron (
  origen text primary key,
  nombre text not null,
  grupo_muscular text not null,
  categorias text[] not null,
  imagen_url text not null
);

insert into carga_fitcron (origen, nombre, grupo_muscular, categorias, imagen_url) values
  ('fitcron-1', 'Crunch Inferior en círculos', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-1.webp'),
  ('fitcron-2', 'Crunch Superior Concentrado Elevado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-2.webp'),
  ('fitcron-3', 'Crunch Cruzado estirado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-3.webp'),
  ('fitcron-4', 'Crunch Inferior con flexión y extensión', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-4.webp'),
  ('fitcron-5', 'Crunch Inferior Cruzado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-5.webp'),
  ('fitcron-6', 'Elevación de Cadera con piernas estiradas v2', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-6.webp'),
  ('fitcron-7', 'Marcha Horizontal Alterna', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-7.webp'),
  ('fitcron-8', 'Marcha Horizontal Alterna con palmada', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-8.webp'),
  ('fitcron-9', 'Crunch Superior', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-9.webp'),
  ('fitcron-10', 'Crunch Frog', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-10.webp'),
  ('fitcron-11', 'Crunch Inferior sentado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-11.webp'),
  ('fitcron-12', 'Marcha Horizontal Aislada con pierna extendida', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-12.webp'),
  ('fitcron-13', 'Crunch Superior Cruzado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-13.webp'),
  ('fitcron-14', 'Pulse Up', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-14.webp'),
  ('fitcron-15', 'Crunch Horizontal en Silla Romana', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-15.webp'),
  ('fitcron-16', 'Elevación de Piernas con torsión en soporte', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-16.webp'),
  ('fitcron-17', 'Giros Superiores Sentado con peso', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-17.webp'),
  ('fitcron-18', 'Giros Superiores Sentado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-18.webp'),
  ('fitcron-19', 'Crunch Superior Cruzado Concentrado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-19.webp'),
  ('fitcron-20', 'Roll Reverse Crunch', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-20.webp'),
  ('fitcron-21', 'Crunch Superior Declinado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-21.webp'),
  ('fitcron-22', 'Puente Lateral con Abducción de Cadera', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-22.webp'),
  ('fitcron-23', 'Crunch en Decúbito Lateral con curl de bíceps', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-23.webp'),
  ('fitcron-24', 'Crunch Superior Cruzado Concentrado Elevado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-24.webp'),
  ('fitcron-25', 'Half Wipers con piernas estiradas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-25.webp'),
  ('fitcron-26', 'Half Wipers con piernas flexionadas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-26.webp'),
  ('fitcron-27', 'Hollow Hold', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-27.webp'),
  ('fitcron-28', 'Crunch Superior Cruzado Declinado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-28.webp'),
  ('fitcron-29', 'Elevación de Cadera con piernas estiradas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-29.webp'),
  ('fitcron-30', 'Elevación de Cadera con flexión de rodillas v2', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-30.webp'),
  ('fitcron-31', 'Wheel Rollout de rodillas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-31.webp'),
  ('fitcron-32', 'Wheel Rollout de pie', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-32.webp'),
  ('fitcron-33', 'Puente Lateral', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-33.webp'),
  ('fitcron-34', 'Crunch Inferior sentado en banco', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-34.webp'),
  ('fitcron-35', 'Russian Twist', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-35.webp'),
  ('fitcron-36', 'Crunch Lateral Horizontal Concentrado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-36.webp'),
  ('fitcron-37', 'Elevación de Cadera con flexión de rodillas v1', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-37.webp'),
  ('fitcron-38', 'Janda Sit-up', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-38.webp'),
  ('fitcron-39', 'Jackknife Sit-Up', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-39.webp'),
  ('fitcron-40', 'Crunch Inferior Inclinado con piernas estiradas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-40.webp'),
  ('fitcron-41', 'Elevación de Cadera con piernas flexionadas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-41.webp'),
  ('fitcron-42', 'Crunch Inferior Cruzado Alterno', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-42.webp'),
  ('fitcron-43', 'Crunch Cruzado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-43.webp'),
  ('fitcron-44', 'Cocoons', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-44.webp'),
  ('fitcron-45', 'Crunch Inferior con Rodillas Flexionadas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-45.webp'),
  ('fitcron-46', 'Crunch Lateral Horizontal Alterno', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-46.webp'),
  ('fitcron-47', 'Crunch Cruzado con piernas elevadas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-47.webp'),
  ('fitcron-48', 'Crunch Lateral Inclinado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-48.webp'),
  ('fitcron-49', 'Crunch Lateral de pie con Banda', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-49.webp'),
  ('fitcron-50', 'Crunch Inferior en Máquina Smith', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-50.webp'),
  ('fitcron-51', 'Crunch Doble Vertical en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-51.webp'),
  ('fitcron-52', 'Sit Up en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-52.webp'),
  ('fitcron-53', 'Crunch Inferior Horizontal en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-53.webp'),
  ('fitcron-54', 'Crunch Superior Horizontal en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-54.webp'),
  ('fitcron-55', 'Giros Inferiores de Oblicuos en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-55.webp'),
  ('fitcron-56', 'Crunch Superior Vertical Amplio en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-56.webp'),
  ('fitcron-57', 'Crunch Superior Vertical en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-57.webp'),
  ('fitcron-58', 'Giros Superiores de Oblicuos en Máquina', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-58.webp'),
  ('fitcron-59', 'Puente Lateral Declinado Aislada', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-59.webp'),
  ('fitcron-60', 'Puente Lateral Declinado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-60.webp'),
  ('fitcron-61', 'Plancha Lateral Inclinada', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-61.webp'),
  ('fitcron-62', 'Crunch en Plancha Lateral', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-62.webp'),
  ('fitcron-63', 'Plancha Lateral', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-63.webp'),
  ('fitcron-64', 'Plancha con rodillas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-64.webp'),
  ('fitcron-65', 'Plancha', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-65.webp'),
  ('fitcron-66', 'Crunch Lateral en soporte', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-66.webp'),
  ('fitcron-67', 'Elevación de piernas flexionadas en soporte', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-67.webp'),
  ('fitcron-68', 'Elevación de piernas estiradas en soporte', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-68.webp'),
  ('fitcron-69', 'Elevación de piernas alternas Colgado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-69.webp'),
  ('fitcron-70', 'Elevación de piernas laterales Colgado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-70.webp'),
  ('fitcron-71', 'Elevación de piernas flexionadas Colgado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-71.webp'),
  ('fitcron-72', 'Elevación de piernas estiradas Colgado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-72.webp'),
  ('fitcron-73', 'Elevación Total Colgado', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-73.webp'),
  ('fitcron-74', 'Giros de cintura de pie con Banda', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-74.webp'),
  ('fitcron-75', 'Elevación de piernas con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-75.webp'),
  ('fitcron-76', 'Sit Up con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-76.webp'),
  ('fitcron-77', 'Pliegue completo con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-77.webp'),
  ('fitcron-78', 'Crunch Cruzado con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-78.webp'),
  ('fitcron-79', 'Crunch Superior de pie con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-79.webp'),
  ('fitcron-80', 'Crunch Diagonal de pie con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-80.webp'),
  ('fitcron-81', 'Crunch Diagonal de rodillas con Bandas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-81.webp'),
  ('fitcron-82', 'Crunch Diagonal en Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-82.webp'),
  ('fitcron-83', 'Giros de cintura sentado con Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-83.webp'),
  ('fitcron-84', 'Crunch Lateral de pie en Polea Baja', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-84.webp'),
  ('fitcron-85', 'Elevación de piernas colgado con Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-85.webp'),
  ('fitcron-86', 'Crunch Superior de rodillas con Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-86.webp'),
  ('fitcron-87', 'Crunch Inferior en Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-87.webp'),
  ('fitcron-88', 'Pliegue completo entre Poleas', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-88.webp'),
  ('fitcron-89', 'Inclinación diagonal en Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-89.webp'),
  ('fitcron-90', 'Crunch Superior de pie con Polea delante', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-90.webp'),
  ('fitcron-91', 'Crunch Lateral de pie en Polea Alta', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-91.webp'),
  ('fitcron-92', 'Crunch Superior sentado con Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-92.webp'),
  ('fitcron-93', 'Russian Twist en Fitball con Polea', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-93.webp'),
  ('fitcron-94', 'Crunch Lateral con Barra', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-94.webp'),
  ('fitcron-95', 'Giros de cintura doblado con Barra', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-95.webp'),
  ('fitcron-96', 'Giros de cintura sentado con Barra', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-96.webp'),
  ('fitcron-97', 'Crunch Lateral con Mancuerna', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-97.webp'),
  ('fitcron-98', 'Russian Twist con Mancuerna', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-98.webp'),
  ('fitcron-99', 'Abdominales en V con Mancuerna', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-99.webp'),
  ('fitcron-100', 'Puente Lateral con Mancuerna', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-100.webp'),
  ('fitcron-101', 'Giros sentado en Fitball', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-101.webp'),
  ('fitcron-102', 'Sit Up en Fitball', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-102.webp'),
  ('fitcron-103', 'Elevación de piernas en Fitball', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-103.webp'),
  ('fitcron-104', 'Crunch Superior en Fitball', 'Abdominales', array['Zona media'], '/ejercicios/fitcron-104.webp'),
  ('fitcron-105', 'Step Up con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-105.webp'),
  ('fitcron-106', 'Extensión de Gemelo Aislado sentado con Mancuerna', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-106.webp'),
  ('fitcron-107', 'Peso Muerto Rígido con Mancuernas', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-107.webp'),
  ('fitcron-108', 'Extensión de Gemelos de pie con Mancuernas', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-108.webp'),
  ('fitcron-109', 'Cuarto de Sentadilla con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-109.webp'),
  ('fitcron-110', 'Sentadilla a una pierna con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-110.webp'),
  ('fitcron-111', 'Zancada Trasera con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-111.webp'),
  ('fitcron-112', 'Sentadilla Sumo con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-112.webp'),
  ('fitcron-113', 'Zancada Delantera con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-113.webp'),
  ('fitcron-114', 'Peso Muerto con Mancuernas', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-114.webp'),
  ('fitcron-115', 'Media Sentadilla con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-115.webp'),
  ('fitcron-116', 'Zancada Lateral Cruzada con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-116.webp'),
  ('fitcron-117', 'Zancada Lateral con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-117.webp'),
  ('fitcron-118', 'Hip Thrust con Mancuerna', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-118.webp'),
  ('fitcron-119', 'Sentadilla Asistida con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-119.webp'),
  ('fitcron-120', 'Peso Muerto Abierto con Mancuerna', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-120.webp'),
  ('fitcron-121', 'Sentadilla Abierta con Mancuerna', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-121.webp'),
  ('fitcron-122', 'Peso Muerto Rumano con Mancuernas', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-122.webp'),
  ('fitcron-123', 'Peso Muerto a una pierna con Mancuernas', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-123.webp'),
  ('fitcron-124', 'Zancadas con salto', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-124.webp'),
  ('fitcron-125', 'Sentadilla con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-125.webp'),
  ('fitcron-126', 'Sentadilla en Pared con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-126.webp'),
  ('fitcron-127', 'Sentadilla en zancada inclinada con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-127.webp'),
  ('fitcron-128', 'Sentadilla con salto con Mancuernas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-128.webp'),
  ('fitcron-129', 'Step Up con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-129.webp'),
  ('fitcron-130', 'Zancada Lateral Cruzada con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-130.webp'),
  ('fitcron-131', 'Peso Muerto Asistido con Barra', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-131.webp'),
  ('fitcron-132', 'Sentadilla en zancada con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-132.webp'),
  ('fitcron-133', 'Hip Thrust con Barra', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-133.webp'),
  ('fitcron-134', 'Hip Thrust Declinado con Barra', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-134.webp'),
  ('fitcron-135', 'Peso Muerto con Barra', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-135.webp'),
  ('fitcron-136', 'Peso Muerto Sumo con Barra', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-136.webp'),
  ('fitcron-137', 'Peso Muerto a una pierna con Barra', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-137.webp'),
  ('fitcron-138', 'Cuarto de Sentadilla con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-138.webp'),
  ('fitcron-139', 'Sentadilla en zancada inclinada con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-139.webp'),
  ('fitcron-140', 'Zancada Lateral con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-140.webp'),
  ('fitcron-141', 'Saltos rodillas en cuclillas con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-141.webp'),
  ('fitcron-142', 'Sentadilla con salto con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-142.webp'),
  ('fitcron-143', 'Hip Thrust Aislado con Barra', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-143.webp'),
  ('fitcron-144', 'Hip Thrust Inclinado con Barra', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-144.webp'),
  ('fitcron-145', 'Extensión de Cuádriceps con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-145.webp'),
  ('fitcron-146', 'Extensión de Gemelos sentado con Barra', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-146.webp'),
  ('fitcron-147', 'Sentadilla Sumo con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-147.webp'),
  ('fitcron-148', 'Extensión de Gemelos de pie con Barra', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-148.webp'),
  ('fitcron-149', 'Peso Muerto Rumano con Barra', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-149.webp'),
  ('fitcron-150', 'Zancada Trasera con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-150.webp'),
  ('fitcron-151', 'Sentadilla a una pierna con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-151.webp'),
  ('fitcron-152', 'Sentadilla con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-152.webp'),
  ('fitcron-153', 'Buenos días con Barra', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-153.webp'),
  ('fitcron-154', 'Sentadilla Profunda con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-154.webp'),
  ('fitcron-155', 'Media Sentadilla con Barra', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-155.webp'),
  ('fitcron-156', 'Peso Muerto en Punta', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-156.webp'),
  ('fitcron-157', 'Sentadilla en Punta', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-157.webp'),
  ('fitcron-158', 'Zancada Trasera en Punta', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-158.webp'),
  ('fitcron-159', 'Aductor Externo en Máquina', 'Abductores', array['Piernas'], '/ejercicios/fitcron-159.webp'),
  ('fitcron-160', 'Extensión de Gemelos sentado en Máquina', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-160.webp'),
  ('fitcron-161', 'Curl Femoral Vertical en Máquina', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-161.webp'),
  ('fitcron-162', 'Curl Femoral Aislado en Máquina', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-162.webp'),
  ('fitcron-163', 'Sentadilla Sumo Inclinada en Máquina', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-163.webp'),
  ('fitcron-164', 'Sentadilla Cerrada Inclinada en Máquina', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-164.webp'),
  ('fitcron-165', 'Extensión de Gemelos Inclinada en Máquina', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-165.webp'),
  ('fitcron-166', 'Extensión de Gemelos en Prensa', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-166.webp'),
  ('fitcron-167', 'Extensión de Gemelos Concentrada en Máquina', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-167.webp'),
  ('fitcron-168', 'Prensa Inclinada Cerrada', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-168.webp'),
  ('fitcron-169', 'Prensa Inclinada', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-169.webp'),
  ('fitcron-170', 'Curl Femoral Horizontal en Máquina', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-170.webp'),
  ('fitcron-171', 'Extensión de Gemelos en Máquina con carga Inferior', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-171.webp'),
  ('fitcron-172', 'Extensión Trasera en Máquina', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-172.webp'),
  ('fitcron-173', 'Extensión Frontal en Máquina', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-173.webp'),
  ('fitcron-174', 'Aductor Interno Aislado en Máquina', 'Aductores', array['Piernas'], '/ejercicios/fitcron-174.webp'),
  ('fitcron-175', 'Aductor Externo Aislado en Máquina', 'Abductores', array['Piernas'], '/ejercicios/fitcron-175.webp'),
  ('fitcron-176', 'Extensión de Gemelos Declinada en Máquina', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-176.webp'),
  ('fitcron-177', 'Extensión de Gemelos en Máquina con carga Superior', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-177.webp'),
  ('fitcron-178', 'Aductor Interno en Máquina', 'Aductores', array['Piernas'], '/ejercicios/fitcron-178.webp'),
  ('fitcron-179', 'Extensión de Cuádriceps en Máquina', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-179.webp'),
  ('fitcron-180', 'Sentadilla en Máquina', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-180.webp'),
  ('fitcron-181', 'Remo en Supinación en Máquina Smith', 'Espalda', array['Tracción'], '/ejercicios/fitcron-181.webp'),
  ('fitcron-182', 'Remo Aislado en Pronación en Máquina Smith', 'Espalda', array['Tracción'], '/ejercicios/fitcron-182.webp'),
  ('fitcron-183', 'Hiperextensiones en Máquina', 'Lumbar', array['Zona media'], '/ejercicios/fitcron-183.webp'),
  ('fitcron-184', 'Curl Femoral Libre', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-184.webp'),
  ('fitcron-185', 'Step Up Lateral', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-185.webp'),
  ('fitcron-186', 'Extensión de Gemelos sentado con Mancuerna', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-186.webp'),
  ('fitcron-187', 'Extensión de Gemelos de pie', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-187.webp'),
  ('fitcron-188', 'Sentadilla a una pierna con Banda Delante', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-188.webp'),
  ('fitcron-189', 'Peso Muerto con Bandas', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-189.webp'),
  ('fitcron-190', 'Rotación de Cadera Interna con Banda', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-190.webp'),
  ('fitcron-191', 'Rotación de Cadera Externa con Banda', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-191.webp'),
  ('fitcron-192', 'Extensión de Gemelo Aislado con Banda', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-192.webp'),
  ('fitcron-193', 'Extensión de Gemelo Aislado Delantero con Banda', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-193.webp'),
  ('fitcron-194', 'Sentadilla a una pierna con Banda Debajo', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-194.webp'),
  ('fitcron-195', 'Sentadilla con Banda', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-195.webp'),
  ('fitcron-196', 'Step Up con Banda', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-196.webp'),
  ('fitcron-197', 'Peso Muerto con Banda', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-197.webp'),
  ('fitcron-198', 'Rotación de Aductor Interna con Banda', 'Aductores', array['Piernas'], '/ejercicios/fitcron-198.webp'),
  ('fitcron-199', 'Rotación de Aductor Externa con Banda', 'Aductores', array['Piernas'], '/ejercicios/fitcron-199.webp'),
  ('fitcron-200', 'Hip Thrust con Banda', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-200.webp'),
  ('fitcron-201', 'Extensión Frontal Aislada con Banda', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-201.webp'),
  ('fitcron-202', 'Extensión de Gemelos con Banda', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-202.webp'),
  ('fitcron-203', 'Extensión de Cuádriceps Aislada con Banda', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-203.webp'),
  ('fitcron-204', 'Sentadilla Aislada Asistida con Cuerda', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-204.webp'),
  ('fitcron-205', 'Extensión Trasera Aislada en Polea Baja', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-205.webp'),
  ('fitcron-206', 'Peso Muerto en Polea', 'Isquiotibiales', array['Piernas', 'Multiarticulares'], '/ejercicios/fitcron-206.webp'),
  ('fitcron-207', 'Extensión de Gemelo Aislado en Polea', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-207.webp'),
  ('fitcron-208', 'Extensión de Gemelos en Polea', 'Gemelos', array['Piernas'], '/ejercicios/fitcron-208.webp'),
  ('fitcron-209', 'Curl Femoral Vertical en Polea', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-209.webp'),
  ('fitcron-210', 'Aductor Externo en Polea', 'Abductores', array['Piernas'], '/ejercicios/fitcron-210.webp'),
  ('fitcron-211', 'Curl Femoral Libre Asistido con Polea', 'Isquiotibiales', array['Piernas'], '/ejercicios/fitcron-211.webp'),
  ('fitcron-212', 'Zancada Delantera en Polea', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-212.webp'),
  ('fitcron-213', 'Zancada Lateral en Polea', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-213.webp'),
  ('fitcron-214', 'Extensión de Glúteos en Polea', 'Glúteos', array['Piernas'], '/ejercicios/fitcron-214.webp'),
  ('fitcron-215', 'Zancada Trasera en Polea', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-215.webp'),
  ('fitcron-216', 'Sentadilla con Poleas', 'Cuádriceps', array['Piernas'], '/ejercicios/fitcron-216.webp'),
  ('fitcron-217', 'Aductor Interno en Polea Baja', 'Aductores', array['Piernas'], '/ejercicios/fitcron-217.webp'),
  ('fitcron-218', 'Remo Declinado en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-218.webp'),
  ('fitcron-219', 'Remo Declinado Neutro en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-219.webp'),
  ('fitcron-220', 'Remo Horizontal Cerrado Neutro Amplio en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-220.webp'),
  ('fitcron-221', 'Extensiones Cruzadas en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-221.webp'),
  ('fitcron-222', 'Serratos con giro en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-222.webp'),
  ('fitcron-223', 'Jalón Cerrado Neutro en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-223.webp'),
  ('fitcron-224', 'Remo Horizontal Cerrado Neutro en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-224.webp'),
  ('fitcron-225', 'Remo Inferior Aislado en Polea Baja', 'Espalda', array['Tracción'], '/ejercicios/fitcron-225.webp'),
  ('fitcron-226', 'Serratos Aislados en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-226.webp'),
  ('fitcron-227', 'Remo Superior en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-227.webp'),
  ('fitcron-228', 'Jalón Abierto Doble Neutro en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-228.webp'),
  ('fitcron-229', 'Remo Inferior en Pronación en Polea Baja', 'Espalda', array['Tracción'], '/ejercicios/fitcron-229.webp'),
  ('fitcron-230', 'Serratos Inclinados con Barra en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-230.webp'),
  ('fitcron-231', 'Rotación Vertical Aislada en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-231.webp'),
  ('fitcron-232', 'Jalón Abierto Neutro en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-232.webp'),
  ('fitcron-233', 'Remo Cruzado en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-233.webp'),
  ('fitcron-234', 'Remo Declinado Abierto en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-234.webp'),
  ('fitcron-235', 'Remo Superior con Cuerda en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-235.webp'),
  ('fitcron-236', 'Serratos Inclinados Cerrados con Barra en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-236.webp'),
  ('fitcron-237', 'Jalón Cerrado con Cuerda en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-237.webp'),
  ('fitcron-238', 'Remo Horizontal en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-238.webp'),
  ('fitcron-239', 'Jalón Aislado Prono-Supino en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-239.webp'),
  ('fitcron-240', 'Jalón Abierto en Pronación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-240.webp'),
  ('fitcron-241', 'Jalón en Pronación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-241.webp'),
  ('fitcron-242', 'Remo Horizontal Superior con Cuerda en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-242.webp'),
  ('fitcron-243', 'Jalón Trasero Abierto en Pronación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-243.webp'),
  ('fitcron-244', 'Jalón en Supinación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-244.webp'),
  ('fitcron-245', 'Jalón Cerrado Neutro con Inclinación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-245.webp'),
  ('fitcron-246', 'Extensión Diagonal en Polea Baja', 'Espalda', array['Tracción'], '/ejercicios/fitcron-246.webp'),
  ('fitcron-247', 'Serratos Inferiores con Barra en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-247.webp'),
  ('fitcron-248', 'Jalón Abierto en Supinación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-248.webp'),
  ('fitcron-249', 'Jalón Cerrado en Pronación en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-249.webp'),
  ('fitcron-250', 'Jalón Aislado Prono-Neutro en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-250.webp'),
  ('fitcron-251', 'Serratos con Cuerda en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-251.webp'),
  ('fitcron-252', 'Remo Horizontal Neutro en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-252.webp'),
  ('fitcron-253', 'Remo Horizontal Abierto en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-253.webp'),
  ('fitcron-254', 'Remo con giro Aislado en Polea Baja', 'Espalda', array['Tracción'], '/ejercicios/fitcron-254.webp'),
  ('fitcron-255', 'Remo Horizontal Aislado en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-255.webp'),
  ('fitcron-256', 'Remo Superior Aislado en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-256.webp'),
  ('fitcron-257', 'Remo Horizontal Cerrado en Pronación en Polea', 'Espalda', array['Tracción'], '/ejercicios/fitcron-257.webp'),
  ('fitcron-258', 'Jalón Aislado en Polea Alta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-258.webp'),
  ('fitcron-259', 'Remo Inferior Aislado con Banda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-259.webp'),
  ('fitcron-260', 'Remo Superior Aislado con Banda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-260.webp'),
  ('fitcron-261', 'Remo Horizontal Aislado con Banda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-261.webp'),
  ('fitcron-262', 'Jalón en Supinación con Bandas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-262.webp'),
  ('fitcron-263', 'Jalón Neutro con Bandas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-263.webp'),
  ('fitcron-264', 'Remo Declinado Alterno con Bandas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-264.webp'),
  ('fitcron-265', 'Remo Horizontal con Bandas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-265.webp'),
  ('fitcron-266', 'Remo Libre Declinado con Cuerdas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-266.webp'),
  ('fitcron-267', 'Remo Libre Horizontal Abierto con Cuerdas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-267.webp'),
  ('fitcron-268', 'Remo Inclinado Alterno con Bandas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-268.webp'),
  ('fitcron-269', 'Remo Libre Inclinado Abierto con Cuerda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-269.webp'),
  ('fitcron-270', 'Remo Libre Inclinado Cerrado con Cuerda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-270.webp'),
  ('fitcron-271', 'Remo Libre Horizontal Cerrado con Cuerda', 'Espalda', array['Tracción'], '/ejercicios/fitcron-271.webp'),
  ('fitcron-272', 'Press Militar Neutro Alterno en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-272.webp'),
  ('fitcron-273', 'Elevación Frontal Aislada en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-273.webp'),
  ('fitcron-274', 'Elevación Frontal en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-274.webp'),
  ('fitcron-275', 'Elevación Lateral Aislada en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-275.webp'),
  ('fitcron-276', 'Press Militar en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-276.webp'),
  ('fitcron-277', 'Encogimientos en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-277.webp'),
  ('fitcron-278', 'Rotación Externa Aislada en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-278.webp'),
  ('fitcron-279', 'Remo al mentón en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-279.webp'),
  ('fitcron-280', 'Rotación Interna Aislada en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-280.webp'),
  ('fitcron-281', 'Elevación Lateral Horizontal en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-281.webp'),
  ('fitcron-282', 'Remo Superior en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-282.webp'),
  ('fitcron-283', 'Elevación Lateral Concentrada en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-283.webp'),
  ('fitcron-284', 'Pájaros Aislados en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-284.webp'),
  ('fitcron-285', 'Press Militar Cerrado en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-285.webp'),
  ('fitcron-286', 'Elevación Frontal Inclinada en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-286.webp'),
  ('fitcron-287', 'Remo al mentón Horizontal en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-287.webp'),
  ('fitcron-288', 'Encogimientos Horizontales en Polea', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-288.webp'),
  ('fitcron-289', 'Elevación Frontal Horizontal en Polea', 'Hombros', array['Empuje'], '/ejercicios/fitcron-289.webp'),
  ('fitcron-290', 'Press Militar con Bandas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-290.webp'),
  ('fitcron-291', 'Extensiones Laterales Amplias con Banda', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-291.webp'),
  ('fitcron-292', 'Elevaciones Completas con Bandas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-292.webp'),
  ('fitcron-293', 'Encogimientos con Banda', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-293.webp'),
  ('fitcron-294', 'Remo Superior con Bandas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-294.webp'),
  ('fitcron-295', 'Elevaciones Laterales con Banda', 'Hombros', array['Empuje'], '/ejercicios/fitcron-295.webp'),
  ('fitcron-296', 'Remo al mentón con Banda', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-296.webp'),
  ('fitcron-297', 'Elevaciones Frontales con Banda', 'Hombros', array['Empuje'], '/ejercicios/fitcron-297.webp'),
  ('fitcron-298', 'Extensiones Laterales con Banda', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-298.webp'),
  ('fitcron-299', 'Press Militar Trasero con Bandas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-299.webp'),
  ('fitcron-300', 'Press Militar Aislado con Banda', 'Hombros', array['Empuje'], '/ejercicios/fitcron-300.webp'),
  ('fitcron-301', 'Pájaros de pie con Bandas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-301.webp'),
  ('fitcron-302', 'Elevación Lateral Aislada con Banda', 'Hombros', array['Empuje'], '/ejercicios/fitcron-302.webp'),
  ('fitcron-303', 'Encogimientos en Paralelas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-303.webp'),
  ('fitcron-304', 'Encogimientos Libres en Banco', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-304.webp'),
  ('fitcron-305', 'Flexiones Verticales entre Bancos', 'Hombros', array['Empuje'], '/ejercicios/fitcron-305.webp'),
  ('fitcron-306', 'Flexiones Verticales con Banco', 'Hombros', array['Empuje'], '/ejercicios/fitcron-306.webp'),
  ('fitcron-307', 'Press Militar Libre', 'Hombros', array['Empuje'], '/ejercicios/fitcron-307.webp'),
  ('fitcron-308', 'Press Militar Libre entre Bancos', 'Hombros', array['Empuje'], '/ejercicios/fitcron-308.webp'),
  ('fitcron-309', 'Press Militar Declinado en Pronación en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-309.webp'),
  ('fitcron-310', 'Aperturas Traseras Neutras en Máquina', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-310.webp'),
  ('fitcron-311', 'Aperturas Traseras en Pronación en Máquina', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-311.webp'),
  ('fitcron-312', 'Press Aislado en Punta', 'Hombros', array['Empuje'], '/ejercicios/fitcron-312.webp'),
  ('fitcron-313', 'Press Militar Inclinado en Pronación en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-313.webp'),
  ('fitcron-314', 'Encogimientos en Máquina', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-314.webp'),
  ('fitcron-315', 'Encogimientos Concentrados en Máquina', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-315.webp'),
  ('fitcron-316', 'Press Militar Inclinado Neutro en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-316.webp'),
  ('fitcron-317', 'Press Militar en Pronación en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-317.webp'),
  ('fitcron-318', 'Press Militar Neutro en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-318.webp'),
  ('fitcron-319', 'Elevación Lateral en Punta', 'Hombros', array['Empuje'], '/ejercicios/fitcron-319.webp'),
  ('fitcron-320', 'Elevaciones Laterales en Máquina', 'Hombros', array['Empuje'], '/ejercicios/fitcron-320.webp'),
  ('fitcron-321', 'Press Arnold Abierto con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-321.webp'),
  ('fitcron-322', 'Encogimientos Declinados con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-322.webp'),
  ('fitcron-323', 'Elevación Frontal con Mancuerna', 'Hombros', array['Empuje'], '/ejercicios/fitcron-323.webp'),
  ('fitcron-324', 'Elevaciones Frontales en Pronación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-324.webp'),
  ('fitcron-325', 'Elevaciones Laterales en Supinación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-325.webp'),
  ('fitcron-326', 'Elevación Lateral Inclinada Aislada con Mancuerna', 'Hombros', array['Empuje'], '/ejercicios/fitcron-326.webp'),
  ('fitcron-327', 'Elevaciones Frontales Inclinadas con giro con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-327.webp'),
  ('fitcron-328', 'Encogimientos Inclinados con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-328.webp'),
  ('fitcron-329', 'Elevación Lateral Horizontal Aislada con Mancuerna', 'Hombros', array['Empuje'], '/ejercicios/fitcron-329.webp'),
  ('fitcron-330', 'Encogimientos Laterales con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-330.webp'),
  ('fitcron-331', 'Elevaciones Completas con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-331.webp'),
  ('fitcron-332', 'Press Militar en Pronación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-332.webp'),
  ('fitcron-333', 'Press Militar Neutro con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-333.webp'),
  ('fitcron-334', 'Remo al mentón con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-334.webp'),
  ('fitcron-335', 'Press Militar con giro con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-335.webp'),
  ('fitcron-336', 'Rotación Vertical Aislada con Mancuerna', 'Hombros', array['Empuje'], '/ejercicios/fitcron-336.webp'),
  ('fitcron-337', 'Elevaciones Frontales Inclinadas en Pronación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-337.webp'),
  ('fitcron-338', 'Elevaciones Laterales Declinadas con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-338.webp'),
  ('fitcron-339', 'Pájaros Aislados con Mancuerna', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-339.webp'),
  ('fitcron-340', 'Remo Superior Aislado con Mancuerna', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-340.webp'),
  ('fitcron-341', 'Pájaros sentado con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-341.webp'),
  ('fitcron-342', 'Pájaros de pie con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-342.webp'),
  ('fitcron-343', 'Elevaciones Laterales Declinadas en Pronación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-343.webp'),
  ('fitcron-344', 'Elevaciones Laterales Declinadas Neutras con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-344.webp'),
  ('fitcron-345', 'Elevaciones Laterales Horizontales con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-345.webp'),
  ('fitcron-346', 'Rotación Externa Aislada con Mancuerna', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-346.webp'),
  ('fitcron-347', 'Press Cubano Circular con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-347.webp'),
  ('fitcron-348', 'Elevaciones Lateral - Frontal con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-348.webp'),
  ('fitcron-349', 'Encogimientos con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-349.webp'),
  ('fitcron-350', 'Press Arnold con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-350.webp'),
  ('fitcron-351', 'Elevaciones Circulares con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-351.webp'),
  ('fitcron-352', 'Press Scott con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-352.webp'),
  ('fitcron-353', 'Elevaciones Laterales Delanteras con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-353.webp'),
  ('fitcron-354', 'Press Horizontal con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-354.webp'),
  ('fitcron-355', 'Remo Superior Trasero con Mancuernas', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-355.webp'),
  ('fitcron-356', 'Elevaciones Laterales Declinadas en Supinación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-356.webp'),
  ('fitcron-357', 'Elevaciones Lateral - Frontal Alto con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-357.webp'),
  ('fitcron-358', 'Press Cubano con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-358.webp'),
  ('fitcron-359', 'Rotación Externa Concentrada con Mancuerna', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-359.webp'),
  ('fitcron-360', 'Elevaciones Frontales en Supinación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-360.webp'),
  ('fitcron-361', 'Elevación Frontal Declinada con Mancuerna', 'Hombros', array['Empuje'], '/ejercicios/fitcron-361.webp'),
  ('fitcron-362', 'Encogimiento Aislado con Mancuerna', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-362.webp'),
  ('fitcron-363', 'Elevaciones Frontales Declinadas Neutras con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-363.webp'),
  ('fitcron-364', 'Press Militar en Supinación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-364.webp'),
  ('fitcron-365', 'Elevaciones Laterales Neutras con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-365.webp'),
  ('fitcron-366', 'Elevaciones Frontales Declinadas en Pronación con Mancuernas', 'Hombros', array['Empuje'], '/ejercicios/fitcron-366.webp'),
  ('fitcron-367', 'Elevación Trasera con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-367.webp'),
  ('fitcron-368', 'Extensión Trasera con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-368.webp'),
  ('fitcron-369', 'Elevación Completa con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-369.webp'),
  ('fitcron-370', 'Remo al mentón Cerrado con Barra Z', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-370.webp'),
  ('fitcron-371', 'Press Militar Trasero con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-371.webp'),
  ('fitcron-372', 'Press Militar con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-372.webp'),
  ('fitcron-373', 'Press Militar en Supinación con Barra Z', 'Hombros', array['Empuje'], '/ejercicios/fitcron-373.webp'),
  ('fitcron-374', 'Elevación Frontal Cerrada en Pronación con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-374.webp'),
  ('fitcron-375', 'Remo al mentón con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-375.webp'),
  ('fitcron-376', 'Elevación Frontal Declinada Abierta con Barra Z', 'Hombros', array['Empuje'], '/ejercicios/fitcron-376.webp'),
  ('fitcron-377', 'Press Militar Mixto con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-377.webp'),
  ('fitcron-378', 'Press Militar Cerrado con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-378.webp'),
  ('fitcron-379', 'Encogimientos en Press Militar con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-379.webp'),
  ('fitcron-380', 'Press Militar Abierto con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-380.webp'),
  ('fitcron-381', 'Elevación Frontal Declinada en Pronación con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-381.webp'),
  ('fitcron-382', 'Encogimientos Delanteros con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-382.webp'),
  ('fitcron-383', 'Encogimientos Traseros con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-383.webp'),
  ('fitcron-384', 'Encogimientos Sentado con Barra', 'Hombros', array['Empuje', 'Tracción'], '/ejercicios/fitcron-384.webp'),
  ('fitcron-385', 'Elevación Frontal con giros con Barra Z', 'Hombros', array['Empuje'], '/ejercicios/fitcron-385.webp'),
  ('fitcron-386', 'Elevación Frontal en Pronación con Barra', 'Hombros', array['Empuje'], '/ejercicios/fitcron-386.webp'),
  ('fitcron-387', 'Elevación Frontal Inclinada en Supinación con Barra Z', 'Hombros', array['Empuje'], '/ejercicios/fitcron-387.webp'),
  ('fitcron-388', 'Jalón en Pronación en Máquina', 'Espalda', array['Tracción'], '/ejercicios/fitcron-388.webp'),
  ('fitcron-389', 'Jalón en Supinación en Máquina', 'Espalda', array['Tracción'], '/ejercicios/fitcron-389.webp'),
  ('fitcron-390', 'Remo Horizontal en Pronación en Máquina', 'Espalda', array['Tracción'], '/ejercicios/fitcron-390.webp'),
  ('fitcron-391', 'Remo Horizontal en Supinación en Máquina', 'Espalda', array['Tracción'], '/ejercicios/fitcron-391.webp'),
  ('fitcron-392', 'Remo Horizontal Neutro en Máquina', 'Espalda', array['Tracción'], '/ejercicios/fitcron-392.webp'),
  ('fitcron-393', 'Remo en Barra T en Supinación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-393.webp'),
  ('fitcron-394', 'Remo en Barra T en Pronación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-394.webp'),
  ('fitcron-395', 'Remo en Punta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-395.webp'),
  ('fitcron-396', 'Remo Aislado en Punta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-396.webp'),
  ('fitcron-397', 'Remo Aislado Neutro en Máquina Smith', 'Espalda', array['Tracción'], '/ejercicios/fitcron-397.webp'),
  ('fitcron-398', 'Dominada Invertida', 'Espalda', array['Tracción'], '/ejercicios/fitcron-398.webp'),
  ('fitcron-399', 'Dominada Mixta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-399.webp'),
  ('fitcron-400', 'Dominada a una mano asistida', 'Espalda', array['Tracción'], '/ejercicios/fitcron-400.webp'),
  ('fitcron-401', 'Dominada Cerrada Corta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-401.webp'),
  ('fitcron-402', 'Dominada en Supinación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-402.webp'),
  ('fitcron-403', 'Dominada Trasera', 'Espalda', array['Tracción'], '/ejercicios/fitcron-403.webp'),
  ('fitcron-404', 'Dominada', 'Espalda', array['Tracción'], '/ejercicios/fitcron-404.webp'),
  ('fitcron-405', 'Dominada Cerrada', 'Espalda', array['Tracción'], '/ejercicios/fitcron-405.webp'),
  ('fitcron-406', 'Dominada Cerrada en Martillo', 'Espalda', array['Tracción'], '/ejercicios/fitcron-406.webp'),
  ('fitcron-407', 'Dominada Abierta', 'Espalda', array['Tracción'], '/ejercicios/fitcron-407.webp'),
  ('fitcron-408', 'Dominada a una mano', 'Espalda', array['Tracción'], '/ejercicios/fitcron-408.webp'),
  ('fitcron-409', 'Dominada Lateral', 'Espalda', array['Tracción'], '/ejercicios/fitcron-409.webp'),
  ('fitcron-410', 'Dominada Circular en Supinación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-410.webp'),
  ('fitcron-411', 'Retracción Escapular Colgado', 'Espalda', array['Tracción'], '/ejercicios/fitcron-411.webp'),
  ('fitcron-412', 'Retracción Escapular entre Bancos', 'Espalda', array['Tracción'], '/ejercicios/fitcron-412.webp'),
  ('fitcron-413', 'Remo Colgado en Supinación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-413.webp'),
  ('fitcron-414', 'Remo Colgado en Pronación', 'Espalda', array['Tracción'], '/ejercicios/fitcron-414.webp'),
  ('fitcron-415', 'Hiperextensiones', 'Lumbar', array['Zona media'], '/ejercicios/fitcron-415.webp'),
  ('fitcron-416', 'Hiperextensiones Inclinadas', 'Lumbar', array['Zona media'], '/ejercicios/fitcron-416.webp'),
  ('fitcron-417', 'Brazada en Fitball', 'Lumbar', array['Zona media'], '/ejercicios/fitcron-417.webp'),
  ('fitcron-418', 'Hiperextensiones en Fitball', 'Lumbar', array['Zona media'], '/ejercicios/fitcron-418.webp'),
  ('fitcron-419', 'Remo Aislado con Mancuerna', 'Espalda', array['Tracción'], '/ejercicios/fitcron-419.webp'),
  ('fitcron-420', 'Pullover con Mancuerna (espalda)', 'Espalda', array['Tracción'], '/ejercicios/fitcron-420.webp'),
  ('fitcron-421', 'Remo Inclinado Neutro con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-421.webp'),
  ('fitcron-422', 'Remo Inclinado en Pronación con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-422.webp'),
  ('fitcron-423', 'Remo Inclinado en Supinación con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-423.webp'),
  ('fitcron-424', 'Remo Neutro con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-424.webp'),
  ('fitcron-425', 'Remo en Pronación con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-425.webp'),
  ('fitcron-426', 'Remo en Supinación con Mancuernas', 'Espalda', array['Tracción'], '/ejercicios/fitcron-426.webp'),
  ('fitcron-427', 'Pullover con Barra Z', 'Espalda', array['Tracción'], '/ejercicios/fitcron-427.webp'),
  ('fitcron-428', 'Remo Aislado con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-428.webp'),
  ('fitcron-429', 'Remo Inclinado en Supinación con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-429.webp'),
  ('fitcron-430', 'Remo Inclinado en Pronación con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-430.webp'),
  ('fitcron-431', 'Remo en Supinación con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-431.webp'),
  ('fitcron-432', 'Remo en Pronación con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-432.webp'),
  ('fitcron-433', 'Remo en Pronación Abierto con Barra', 'Espalda', array['Tracción'], '/ejercicios/fitcron-433.webp'),
  ('fitcron-434', 'Extensión Concentrada en Polea Baja', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-434.webp'),
  ('fitcron-435', 'Extensión Concentrada en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-435.webp'),
  ('fitcron-436', 'Press Francés Inclinado con Polea', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-436.webp'),
  ('fitcron-437', 'Extensión Vertical Neutra en Polea Baja', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-437.webp'),
  ('fitcron-438', 'Extensión Trasera Aislada en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-438.webp'),
  ('fitcron-439', 'Extensión Vertical Aislada en Supinación en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-439.webp'),
  ('fitcron-440', 'Extensión Vertical en Pronación en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-440.webp'),
  ('fitcron-441', 'Patadas Traseras en Polea', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-441.webp'),
  ('fitcron-442', 'Extensión Vertical Neutra en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-442.webp'),
  ('fitcron-443', 'Extensiones Concentradas en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-443.webp'),
  ('fitcron-444', 'Press Francés con Polea', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-444.webp'),
  ('fitcron-445', 'Extensión Lateral Aislada en Supinación en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-445.webp'),
  ('fitcron-446', 'Extensión Vertical en Supinación en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-446.webp'),
  ('fitcron-447', 'Extensión Vertical Aislada en Pronación en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-447.webp'),
  ('fitcron-448', 'Extensión Horizontal en Martillo en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-448.webp'),
  ('fitcron-449', 'Press Francés Neutro con Polea', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-449.webp'),
  ('fitcron-450', 'Extensión Vertical en Pronación en Polea Baja', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-450.webp'),
  ('fitcron-451', 'Extensión Vertical Aislada en Pronación en Polea Baja', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-451.webp'),
  ('fitcron-452', 'Extensión Frontal Aislada en Polea Alta', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-452.webp'),
  ('fitcron-453', 'Extensiones Cruzadas en Polea', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-453.webp'),
  ('fitcron-454', 'Curl en Martillo en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-454.webp'),
  ('fitcron-455', 'Curl Vertical en Supinación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-455.webp'),
  ('fitcron-456', 'Curl Aislado en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-456.webp'),
  ('fitcron-457', 'Curl en Banco Scott en Supinación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-457.webp'),
  ('fitcron-458', 'Curl en Banco Scott en Pronación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-458.webp'),
  ('fitcron-459', 'Curl en Martillo en Polea Alta', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-459.webp'),
  ('fitcron-460', 'Curl en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-460.webp'),
  ('fitcron-461', 'Curl Lateral en Supinación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-461.webp'),
  ('fitcron-462', 'Curl Lateral en Supinación Aislado con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-462.webp'),
  ('fitcron-463', 'Curl Aislado en Pronación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-463.webp'),
  ('fitcron-464', 'Curl en Pronación con agarre Z en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-464.webp'),
  ('fitcron-465', 'Curl en Supinación con agarre Z en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-465.webp'),
  ('fitcron-466', 'Curl Concentrado Lateral Aislado en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-466.webp'),
  ('fitcron-467', 'Curl en Banco Scott Neutro con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-467.webp'),
  ('fitcron-468', 'Curl en Banco Scott Neutro Aislado con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-468.webp'),
  ('fitcron-469', 'Curl en Supinación en Polea Alta', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-469.webp'),
  ('fitcron-470', 'Curl Horizontal Cerrado en Supinación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-470.webp'),
  ('fitcron-471', 'Curl en Banco Scott en Pronación Aislado con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-471.webp'),
  ('fitcron-472', 'Curl en Banco Scott en Supinación Aislado con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-472.webp'),
  ('fitcron-473', 'Curl en Supinación Retraído en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-473.webp'),
  ('fitcron-474', 'Curl Concentrado Cerrado en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-474.webp'),
  ('fitcron-475', 'Curl en Supinación Cerrado en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-475.webp'),
  ('fitcron-476', 'Curl Horizontal Inclinado con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-476.webp'),
  ('fitcron-477', 'Curl Concentrado en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-477.webp'),
  ('fitcron-478', 'Curl en V en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-478.webp'),
  ('fitcron-479', 'Curl Horizontal en Supinación con Polea', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-479.webp'),
  ('fitcron-480', 'Curl Aislado Largo en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-480.webp'),
  ('fitcron-481', 'Curl Concentrado Frontal Aislado en Supinación en Polea Baja', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-481.webp'),
  ('fitcron-482', 'Curl con peso libre', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-482.webp'),
  ('fitcron-483', 'Curl Alterno en Supinación en Máquina', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-483.webp'),
  ('fitcron-484', 'Curl Concentrado en Máquina', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-484.webp'),
  ('fitcron-485', 'Curl en Pronación en Máquina Scott', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-485.webp'),
  ('fitcron-486', 'Curl en Martillo en Máquina Scott', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-486.webp'),
  ('fitcron-487', 'Curl en Supinación en Máquina Scott', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-487.webp'),
  ('fitcron-488', 'Curl con giro Alterno con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-488.webp'),
  ('fitcron-489', 'Curl en Martillo Alterno con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-489.webp'),
  ('fitcron-490', 'Curl Inclinado con giro Alterno con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-490.webp'),
  ('fitcron-491', 'Curl Inclinado Lateral con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-491.webp'),
  ('fitcron-492', 'Curl Inclinado Neutro Alterno con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-492.webp'),
  ('fitcron-493', 'Curl Aislado hacia abajo con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-493.webp'),
  ('fitcron-494', 'Curl Aislado en Pronación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-494.webp'),
  ('fitcron-495', 'Curl Horizontal con giro con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-495.webp'),
  ('fitcron-496', 'Curl Concentrado en Supinación con Mancuerna (bíceps)', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-496.webp'),
  ('fitcron-497', 'Curl Concentrado en Pronación con Mancuerna (bíceps)', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-497.webp'),
  ('fitcron-498', 'Curl en Banco Scott en Supinación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-498.webp'),
  ('fitcron-499', 'Curl en Banco Scott en Pronación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-499.webp'),
  ('fitcron-500', 'Curl Horizontal en Supinación con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-500.webp'),
  ('fitcron-501', 'Curl en Martillo Cruzado con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-501.webp'),
  ('fitcron-502', 'Curl Aislado Neutro con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-502.webp'),
  ('fitcron-503', 'Curl Aislado en Supinación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-503.webp'),
  ('fitcron-504', 'Curl Spider Aislado Neutro con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-504.webp'),
  ('fitcron-505', 'Curl Spider Aislado en Pronación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-505.webp'),
  ('fitcron-506', 'Curl Spider Aislado en Supinación con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-506.webp'),
  ('fitcron-507', 'Curl Lateral con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-507.webp'),
  ('fitcron-508', 'Curl en Banco Scott Neutro con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-508.webp'),
  ('fitcron-509', 'Curl Horizontal con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-509.webp'),
  ('fitcron-510', 'Curl Inclinado Alterno en Supinación con Mancuernas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-510.webp'),
  ('fitcron-511', 'Curl Spider Neutro con Mancuerna', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-511.webp'),
  ('fitcron-512', 'Curl en Supinación Cerrado Con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-512.webp'),
  ('fitcron-513', 'Curl en Pronación con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-513.webp'),
  ('fitcron-514', 'Curl en Supinación Corto con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-514.webp'),
  ('fitcron-515', 'Curl en Supinación con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-515.webp'),
  ('fitcron-516', 'Curl Spider en Supinación con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-516.webp'),
  ('fitcron-517', 'Curl Concentrado Cerrado con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-517.webp'),
  ('fitcron-518', 'Curl en Supinación Abierto Con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-518.webp'),
  ('fitcron-519', 'Extensión en caída con Bandas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-519.webp'),
  ('fitcron-520', 'Curl en Supinación Abierto en banco Scott con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-520.webp'),
  ('fitcron-521', 'Curl en Supinación Cerrado en banco Scott con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-521.webp'),
  ('fitcron-522', 'Curl en Pronación en banco Scott con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-522.webp'),
  ('fitcron-523', 'Curl en Supinación hacia abajo con Barra Z', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-523.webp'),
  ('fitcron-524', 'Curl Aislado con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-524.webp'),
  ('fitcron-525', 'Curl en Supinación Retraído con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-525.webp'),
  ('fitcron-526', 'Curl en Supinación con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-526.webp'),
  ('fitcron-527', 'Curl en Pronación Abierto con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-527.webp'),
  ('fitcron-528', 'Curl en Pronación en banco Scott con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-528.webp'),
  ('fitcron-529', 'Curl en Supinación en banco Scott con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-529.webp'),
  ('fitcron-530', 'Curl en Supinación Cerrado con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-530.webp'),
  ('fitcron-531', 'Curl en Pronación con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-531.webp'),
  ('fitcron-532', 'Curl en Martillo con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-532.webp'),
  ('fitcron-533', 'Curl en Supinación hacia abajo con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-533.webp'),
  ('fitcron-534', 'Curl Spider en Supinación con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-534.webp'),
  ('fitcron-535', 'Curl Concentrado Cerrado con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-535.webp'),
  ('fitcron-536', 'Curl en Supinación Abierto Con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-536.webp'),
  ('fitcron-537', 'Curl Concentrado con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-537.webp'),
  ('fitcron-538', 'Curl Spider en Pronación con Barra', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-538.webp'),
  ('fitcron-539', 'Curl en Supinación Concentrado con Banda', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-539.webp'),
  ('fitcron-540', 'Curl en Supinación Aislado con Banda', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-540.webp'),
  ('fitcron-541', 'Curl en caída con Bandas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-541.webp'),
  ('fitcron-542', 'Curl en Supinación Alterno con Bandas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-542.webp'),
  ('fitcron-543', 'Curl en Supinación con Bandas', 'Bíceps', array['Tracción', 'Brazos'], '/ejercicios/fitcron-543.webp'),
  ('fitcron-544', 'Extensión Vertical con Bandas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-544.webp'),
  ('fitcron-545', 'Press Francés con Bandas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-545.webp'),
  ('fitcron-546', 'Extensión hacia abajo con Bandas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-546.webp'),
  ('fitcron-547', 'Extensión Lateral Aislada con Banda', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-547.webp'),
  ('fitcron-548', 'Extensiones Inclinadas con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-548.webp'),
  ('fitcron-549', 'Press Francés con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-549.webp'),
  ('fitcron-550', 'Extensión Horizontal Concentrada Interna con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-550.webp'),
  ('fitcron-551', 'Extensiones Horizontales Internas con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-551.webp'),
  ('fitcron-552', 'Extensión Vertical Aislada con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-552.webp'),
  ('fitcron-553', 'Extensión Declinada con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-553.webp'),
  ('fitcron-554', 'Press Banca Neutro con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-554.webp'),
  ('fitcron-555', 'Extensión Horizontal Concentrada Superior con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-555.webp'),
  ('fitcron-556', 'Press Banca en Supinación Aislado con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-556.webp'),
  ('fitcron-557', 'Press Inclinado Aislado con Mancuerna (tríceps)', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-557.webp'),
  ('fitcron-558', 'Press Declinado Aislado con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-558.webp'),
  ('fitcron-559', 'Press Banca con giro con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-559.webp'),
  ('fitcron-560', 'Press Francés Inclinado Alterno con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-560.webp'),
  ('fitcron-561', 'Patadas Traseras con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-561.webp'),
  ('fitcron-562', 'Patadas Traseras Alternas con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-562.webp'),
  ('fitcron-563', 'Extensión Vertical con Mancuerna', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-563.webp'),
  ('fitcron-564', 'Extensión Delante-Detrás con Mancuernas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-564.webp'),
  ('fitcron-565', 'Press Francés tras nuca con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-565.webp'),
  ('fitcron-566', 'Extensión Horizontal con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-566.webp'),
  ('fitcron-567', 'Press Inclinado en Supinación con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-567.webp'),
  ('fitcron-568', 'Press Francés Declinado con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-568.webp'),
  ('fitcron-569', 'Press Francés Inverso con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-569.webp'),
  ('fitcron-570', 'Press Francés con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-570.webp'),
  ('fitcron-571', 'Press a una mano con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-571.webp'),
  ('fitcron-572', 'Press Cerrado con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-572.webp'),
  ('fitcron-573', 'Press Inclinado Cerrado con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-573.webp'),
  ('fitcron-574', 'Press Cerrado en Supinación con Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-574.webp'),
  ('fitcron-575', 'Extensión Vertical con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-575.webp'),
  ('fitcron-576', 'Extensión Inclinada con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-576.webp'),
  ('fitcron-577', 'Extensión Horizontal con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-577.webp'),
  ('fitcron-578', 'Press Francés con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-578.webp'),
  ('fitcron-579', 'Press Francés Declinado Cerrado con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-579.webp'),
  ('fitcron-580', 'Press Francés Declinado Abierto con Barra Z', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-580.webp'),
  ('fitcron-581', 'Extensiones en Pronación en Máquina', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-581.webp'),
  ('fitcron-582', 'Extensiones en Máquina', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-582.webp'),
  ('fitcron-583', 'Fondos en Máquina (tríceps)', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-583.webp'),
  ('fitcron-584', 'Fondos en Pronación en Máquina', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-584.webp'),
  ('fitcron-585', 'Flexiones en supinación', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-585.webp'),
  ('fitcron-586', 'Flexiones Cruzadas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-586.webp'),
  ('fitcron-587', 'Flexiones Cerradas (tríceps)', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-587.webp'),
  ('fitcron-588', 'Flexiones Básicas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-588.webp'),
  ('fitcron-589', 'Flexiones con codos', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-589.webp'),
  ('fitcron-590', 'Flexiones Diamante', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-590.webp'),
  ('fitcron-591', 'Extensiones en caída libre', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-591.webp'),
  ('fitcron-592', 'Fondos en banco', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-592.webp'),
  ('fitcron-593', 'Fondos entre bancos', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-593.webp'),
  ('fitcron-594', 'Fondos Imposibles', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-594.webp'),
  ('fitcron-595', 'Fondos Coreanos en Barra', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-595.webp'),
  ('fitcron-596', 'Fondos Cerrados en Paralelas', 'Tríceps', array['Empuje', 'Brazos'], '/ejercicios/fitcron-596.webp'),
  ('fitcron-597', 'Pullover Extenso con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-597.webp'),
  ('fitcron-598', 'Pullover con Mancuerna (pecho)', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-598.webp'),
  ('fitcron-599', 'Press Declinado Neutro con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-599.webp'),
  ('fitcron-600', 'Press Declinado con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-600.webp'),
  ('fitcron-601', 'Press Banca con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-601.webp'),
  ('fitcron-602', 'Press Inclinado en Supinación con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-602.webp'),
  ('fitcron-603', 'Press Aislado en Supinación con Mancuerna', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-603.webp'),
  ('fitcron-604', 'Press Inclinado en Supinación con giro con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-604.webp'),
  ('fitcron-605', 'Press Inclinado Aislado con Mancuerna (pecho)', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-605.webp'),
  ('fitcron-606', 'Aperturas Declinadas con giro con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-606.webp'),
  ('fitcron-607', 'Aperturas Declinadas con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-607.webp'),
  ('fitcron-608', 'Aperturas Inclinadas con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-608.webp'),
  ('fitcron-609', 'Aperturas con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-609.webp'),
  ('fitcron-610', 'Press Banca Alterno con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-610.webp'),
  ('fitcron-611', 'Press Abierto Neutro con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-611.webp'),
  ('fitcron-612', 'Press Cerrado Neutro con Mancuernas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-612.webp'),
  ('fitcron-613', 'Press Inclinado Cerrado Neutro con Mancuerna', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-613.webp'),
  ('fitcron-614', 'Flexiones a una mano asistidas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-614.webp'),
  ('fitcron-615', 'Flexiones a una mano', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-615.webp'),
  ('fitcron-616', 'Flexiones Archer', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-616.webp'),
  ('fitcron-617', 'Flexiones Declinadas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-617.webp'),
  ('fitcron-618', 'Flexiones Pliométricas con Palmada', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-618.webp'),
  ('fitcron-619', 'Flexiones Cerradas (pecho)', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-619.webp'),
  ('fitcron-620', 'Flexiones Abiertas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-620.webp'),
  ('fitcron-621', 'Flexiones Pliométricas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-621.webp'),
  ('fitcron-622', 'Flexiones con Soportes', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-622.webp'),
  ('fitcron-623', 'Flexiones', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-623.webp'),
  ('fitcron-624', 'Press Svend', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-624.webp'),
  ('fitcron-625', 'Fondos en Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-625.webp'),
  ('fitcron-626', 'Fondos en Paralelas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-626.webp'),
  ('fitcron-627', 'Aperturas en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-627.webp'),
  ('fitcron-628', 'Aperturas Extendidas en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-628.webp'),
  ('fitcron-629', 'Press Banca en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-629.webp'),
  ('fitcron-630', 'Cruces en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-630.webp'),
  ('fitcron-631', 'Fondos en Máquina (pecho)', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-631.webp'),
  ('fitcron-632', 'Press Frontal Cerrado en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-632.webp'),
  ('fitcron-633', 'Press Frontal Superior en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-633.webp'),
  ('fitcron-634', 'Press Inclinado en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-634.webp'),
  ('fitcron-635', 'Press Frontal Inferior en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-635.webp'),
  ('fitcron-636', 'Press Frontal en Máquina', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-636.webp'),
  ('fitcron-637', 'Apertura Aislada en Punta', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-637.webp'),
  ('fitcron-638', 'Press Declinado con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-638.webp'),
  ('fitcron-639', 'Press Declinado Inverso con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-639.webp'),
  ('fitcron-640', 'Pullover Declinado Cerrado con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-640.webp'),
  ('fitcron-641', 'Press Banca Abierto Inverso con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-641.webp'),
  ('fitcron-642', 'Press Inclinado Inverso con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-642.webp'),
  ('fitcron-643', 'Pullover Declinado con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-643.webp'),
  ('fitcron-644', 'Pullover con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-644.webp'),
  ('fitcron-645', 'Press Cerrado en Máquina Smith', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-645.webp'),
  ('fitcron-646', 'Press Banca Cerrado con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-646.webp'),
  ('fitcron-647', 'Press Banca Abierto con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-647.webp'),
  ('fitcron-648', 'Press Inclinado con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-648.webp'),
  ('fitcron-649', 'Press Banca con Barra', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-649.webp'),
  ('fitcron-650', 'Pullover con cuerda en Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-650.webp'),
  ('fitcron-651', 'Apertura Aislada Declinada con Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-651.webp'),
  ('fitcron-652', 'Press Declinado Aislado con Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-652.webp'),
  ('fitcron-653', 'Cruce completo de Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-653.webp'),
  ('fitcron-654', 'Cruce inferior de Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-654.webp'),
  ('fitcron-655', 'Cruce superior de Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-655.webp'),
  ('fitcron-656', 'Cruce de Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-656.webp'),
  ('fitcron-657', 'Press Inclinado Aislado con Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-657.webp'),
  ('fitcron-658', 'Press Banca Aislado con Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-658.webp'),
  ('fitcron-659', 'Press Frontal a una mano en Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-659.webp'),
  ('fitcron-660', 'Press Frontal con Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-660.webp'),
  ('fitcron-661', 'Press Frontal Cerrado con Poleas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-661.webp'),
  ('fitcron-662', 'Press Frontal Neutral con Polea', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-662.webp'),
  ('fitcron-663', 'Press Banca con Bandas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-663.webp'),
  ('fitcron-664', 'Press Frontal Inclinado con Bandas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-664.webp'),
  ('fitcron-665', 'Aperturas con Bandas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-665.webp'),
  ('fitcron-666', 'Press Frontal en Pronación con Bandas', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-666.webp'),
  ('fitcron-667', 'Press Frontal Neutral con Banda', 'Pectorales', array['Empuje'], '/ejercicios/fitcron-667.webp'),
  ('fitcron-668', 'Carrera continua', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-668.webp'),
  ('fitcron-669', 'Burpee', 'Cardio', array['Cardiorrespiratorio', 'Multiarticulares'], '/ejercicios/fitcron-669.webp'),
  ('fitcron-670', 'Burpee con Mancuernas', 'Cardio', array['Cardiorrespiratorio', 'Multiarticulares'], '/ejercicios/fitcron-670.webp'),
  ('fitcron-671', 'Burpee Jack', 'Cardio', array['Cardiorrespiratorio', 'Multiarticulares'], '/ejercicios/fitcron-671.webp'),
  ('fitcron-672', 'Caminar con peso', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-672.webp'),
  ('fitcron-673', 'Caminar', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-673.webp'),
  ('fitcron-674', 'Paso lateral con Banda', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-674.webp'),
  ('fitcron-675', 'Caminar a paso ligero', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-675.webp'),
  ('fitcron-676', 'Butt Kicks', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-676.webp'),
  ('fitcron-677', 'Split Jacks', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-677.webp'),
  ('fitcron-678', 'Mountain Climbers', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-678.webp'),
  ('fitcron-679', 'Carrera de skater', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-679.webp'),
  ('fitcron-680', 'Plyo Jacks', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-680.webp'),
  ('fitcron-681', 'Jumping Jacks', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-681.webp'),
  ('fitcron-682', 'Rodilla al codo con sentadilla', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-682.webp'),
  ('fitcron-683', 'Rodilla al codo', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-683.webp'),
  ('fitcron-684', 'Rodilla al codo con giro', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-684.webp'),
  ('fitcron-685', 'Pies rápidos de pie', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-685.webp'),
  ('fitcron-686', 'Salto alterno en el sitio', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-686.webp'),
  ('fitcron-687', 'Carrera en zigzag', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-687.webp'),
  ('fitcron-688', 'Skips', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-688.webp'),
  ('fitcron-689', 'Carrera rápida en el sitio', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-689.webp'),
  ('fitcron-690', 'Elevación de rodillas con apoyo', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-690.webp'),
  ('fitcron-691', 'Pies rápidos agachado', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-691.webp'),
  ('fitcron-692', 'Patadas altas', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-692.webp'),
  ('fitcron-693', 'Carrera con salto', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-693.webp'),
  ('fitcron-694', 'Carrera de pasos cortos', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-694.webp'),
  ('fitcron-695', 'Caminar con rodilla arriba', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-695.webp'),
  ('fitcron-696', 'Salto con desplazamiento lateral cruzado', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-696.webp'),
  ('fitcron-697', 'Salto de esquí', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-697.webp'),
  ('fitcron-698', 'Salto con desplazamiento lateral', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-698.webp'),
  ('fitcron-699', 'Golpes alternos', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-699.webp'),
  ('fitcron-700', 'Desplazamientos de Boxeo', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-700.webp'),
  ('fitcron-701', 'Elevación de rodillas', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-701.webp'),
  ('fitcron-702', 'Zancada con salto', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-702.webp'),
  ('fitcron-703', 'Squat Tuck Jumps', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-703.webp'),
  ('fitcron-704', 'Tuck Jumps', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-704.webp'),
  ('fitcron-705', 'Sprints con rodilla alta', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-705.webp'),
  ('fitcron-706', 'Step Up', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-706.webp'),
  ('fitcron-707', 'Carrera hacia atrás', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-707.webp'),
  ('fitcron-708', 'Caminar en cuclillas', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-708.webp'),
  ('fitcron-709', 'Máquina Escaladora', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-709.webp'),
  ('fitcron-710', 'Máquina Elíptica', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-710.webp'),
  ('fitcron-711', 'Máquina de Step', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-711.webp'),
  ('fitcron-712', 'Krankcycle', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-712.webp'),
  ('fitcron-713', 'Bicicleta Estática Normal', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-713.webp'),
  ('fitcron-714', 'Bicicleta Estática Deportiva', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-714.webp'),
  ('fitcron-715', 'Máquina de Remo', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-715.webp'),
  ('fitcron-716', 'Carrera en Cinta Inclinada', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-716.webp'),
  ('fitcron-717', 'Carrera en Cinta', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-717.webp'),
  ('fitcron-718', 'Bicicleta Estática Reclinada', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-718.webp'),
  ('fitcron-719', 'Air Bike', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-719.webp'),
  ('fitcron-720', 'Salto con Cuerda Alterno Alto', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-720.webp'),
  ('fitcron-721', 'Salto con Cuerda Alterno Normal', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-721.webp'),
  ('fitcron-722', 'Salto con Cuerda Alto', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-722.webp'),
  ('fitcron-723', 'Salto con Cuerda Lateral', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-723.webp'),
  ('fitcron-724', 'Salto con Cuerda Normal', 'Cardio', array['Cardiorrespiratorio'], '/ejercicios/fitcron-724.webp'),
  ('fitcron-725', 'Flexión Frontal con Disco (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-725.webp'),
  ('fitcron-726', 'Extensión Frontal con Disco (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-726.webp'),
  ('fitcron-727', 'Extensión Frontal con Arnés (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-727.webp'),
  ('fitcron-728', 'Extensión Lateral con Arnés (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-728.webp'),
  ('fitcron-729', 'Flexión Frontal en Polea (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-729.webp'),
  ('fitcron-730', 'Extensión Frontal en Polea (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-730.webp'),
  ('fitcron-731', 'Extensión Lateral en Máquina (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-731.webp'),
  ('fitcron-732', 'Extensión Frontal en Máquina (cuello)', 'Cuello', array['Zona media'], '/ejercicios/fitcron-732.webp'),
  ('fitcron-733', 'Curl a una mano en Polea Alta', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-733.webp'),
  ('fitcron-734', 'Curl Vertical en Polea Baja', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-734.webp'),
  ('fitcron-735', 'Curl Concentrado en Supinación con Polea', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-735.webp'),
  ('fitcron-736', 'Curl Concentrado en Pronación con Polea', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-736.webp'),
  ('fitcron-737', 'Hand Grip', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-737.webp'),
  ('fitcron-738', 'Wrist Roller', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-738.webp'),
  ('fitcron-739', 'Rotación Concentrada con Mancuerna', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-739.webp'),
  ('fitcron-740', 'Curl Concentrado Neutral con Mancuerna', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-740.webp'),
  ('fitcron-741', 'Curl Concentrado en Pronación con Mancuerna (antebrazo)', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-741.webp'),
  ('fitcron-742', 'Curl Concentrado en Supinación con Mancuerna (antebrazo)', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-742.webp'),
  ('fitcron-743', 'Curl Inclinado con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-743.webp'),
  ('fitcron-744', 'Curl Vertical en Supinación con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-744.webp'),
  ('fitcron-745', 'Curl Vertical de Dedos con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-745.webp'),
  ('fitcron-746', 'Curl Concentrado de Dedos con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-746.webp'),
  ('fitcron-747', 'Curl Concentrado en Pronación con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-747.webp'),
  ('fitcron-748', 'Curl Concentrado en Supinación con Barra', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-748.webp'),
  ('fitcron-749', 'Curl Concentrado en Pronación con Banda', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-749.webp'),
  ('fitcron-750', 'Curl Concentrado en Supinación con Banda', 'Antebrazo', array['Brazos'], '/ejercicios/fitcron-750.webp');

-- 2) Los que ya existían con el mismo nombre: se usan (no se duplican) ------
with coincidencias as (
  select distinct on (c.origen) c.origen, c.imagen_url, e.id
  from carga_fitcron c
  join public.ejercicios e
    on lower(btrim(e.nombre)) = lower(c.nombre) and e.origen is null
  where not exists (select 1 from public.ejercicios x where x.origen = c.origen)
  order by c.origen, e.creado_en
)
update public.ejercicios e
set origen = m.origen,
    imagen_url = coalesce(e.imagen_url, m.imagen_url)
from coincidencias m
where e.id = m.id;

-- 3) Los nuevos --------------------------------------------------------------
insert into public.ejercicios (origen, nombre, grupo_muscular, categorias, imagen_url)
select c.origen, c.nombre, c.grupo_muscular, c.categorias, c.imagen_url
from carga_fitcron c
where not exists (select 1 from public.ejercicios e where e.origen = c.origen)
  and not exists (select 1 from public.ejercicios e where lower(btrim(e.nombre)) = lower(c.nombre));

drop table if exists pg_temp.carga_fitcron;

-- 4) GIF para los ejercicios de antes que tienen un equivalente claro -------
update public.ejercicios e
set imagen_url = v.imagen_url
from (values
  ('Press banca plano con barra', '/ejercicios/fitcron-649.webp'),
  ('Press banca inclinado con barra', '/ejercicios/fitcron-648.webp'),
  ('Press banca declinado con barra', '/ejercicios/fitcron-638.webp'),
  ('Press banca plano con mancuernas', '/ejercicios/fitcron-601.webp'),
  ('Fondos en paralelas inclinados', '/ejercicios/fitcron-626.webp'),
  ('Flexiones de brazos', '/ejercicios/fitcron-623.webp'),
  ('Flexiones con pies elevados', '/ejercicios/fitcron-617.webp'),
  ('Aperturas con mancuernas', '/ejercicios/fitcron-609.webp'),
  ('Cruce de poleas', '/ejercicios/fitcron-656.webp'),
  ('Pec deck', '/ejercicios/fitcron-627.webp'),
  ('Press militar con barra', '/ejercicios/fitcron-372.webp'),
  ('Press de hombros con mancuernas', '/ejercicios/fitcron-332.webp'),
  ('Press de hombros en máquina', '/ejercicios/fitcron-317.webp'),
  ('Press Arnold', '/ejercicios/fitcron-350.webp'),
  ('Dominadas pronas', '/ejercicios/fitcron-404.webp'),
  ('Dominadas supinas', '/ejercicios/fitcron-402.webp'),
  ('Dominadas neutras', '/ejercicios/fitcron-406.webp'),
  ('Jalón al pecho agarre pronado', '/ejercicios/fitcron-241.webp'),
  ('Jalón al pecho agarre neutro', '/ejercicios/fitcron-223.webp'),
  ('Jalón unilateral en polea', '/ejercicios/fitcron-258.webp'),
  ('Remo con barra', '/ejercicios/fitcron-432.webp'),
  ('Remo con mancuerna', '/ejercicios/fitcron-419.webp'),
  ('Remo en máquina con pecho apoyado', '/ejercicios/fitcron-392.webp'),
  ('Remo sentado en polea', '/ejercicios/fitcron-224.webp'),
  ('Remo unilateral en polea', '/ejercicios/fitcron-255.webp'),
  ('Pájaro con mancuernas', '/ejercicios/fitcron-342.webp'),
  ('Reverse pec deck', '/ejercicios/fitcron-311.webp'),
  ('Sentadilla trasera', '/ejercicios/fitcron-152.webp'),
  ('Prensa de piernas', '/ejercicios/fitcron-169.webp'),
  ('Sentadilla búlgara', '/ejercicios/fitcron-127.webp'),
  ('Zancadas', '/ejercicios/fitcron-113.webp'),
  ('Step-up', '/ejercicios/fitcron-105.webp'),
  ('Extensión de rodilla', '/ejercicios/fitcron-179.webp'),
  ('Peso muerto convencional', '/ejercicios/fitcron-135.webp'),
  ('Peso muerto rumano', '/ejercicios/fitcron-149.webp'),
  ('Peso muerto rumano con mancuernas', '/ejercicios/fitcron-122.webp'),
  ('Hip thrust con barra', '/ejercicios/fitcron-133.webp'),
  ('Extensión lumbar 45°', '/ejercicios/fitcron-416.webp'),
  ('Curl femoral tumbado', '/ejercicios/fitcron-170.webp'),
  ('Curl femoral unilateral', '/ejercicios/fitcron-162.webp'),
  ('Abducción de cadera en máquina', '/ejercicios/fitcron-159.webp'),
  ('Aducción de cadera en máquina', '/ejercicios/fitcron-178.webp'),
  ('Patada de glúteo en polea', '/ejercicios/fitcron-214.webp'),
  ('Elevación de talones de pie', '/ejercicios/fitcron-187.webp'),
  ('Elevación de talones sentado', '/ejercicios/fitcron-160.webp'),
  ('Elevación de talones en prensa', '/ejercicios/fitcron-166.webp'),
  ('Curl con barra', '/ejercicios/fitcron-526.webp'),
  ('Curl con mancuernas', '/ejercicios/fitcron-488.webp'),
  ('Curl inclinado con mancuernas', '/ejercicios/fitcron-510.webp'),
  ('Curl predicador', '/ejercicios/fitcron-529.webp'),
  ('Curl martillo', '/ejercicios/fitcron-489.webp'),
  ('Curl en polea baja', '/ejercicios/fitcron-460.webp'),
  ('Press cerrado', '/ejercicios/fitcron-572.webp'),
  ('Extensión de tríceps en polea', '/ejercicios/fitcron-440.webp'),
  ('Press francés', '/ejercicios/fitcron-570.webp'),
  ('Elevación lateral con mancuernas', '/ejercicios/fitcron-365.webp'),
  ('Elevación lateral en polea', '/ejercicios/fitcron-275.webp'),
  ('Elevación lateral en máquina', '/ejercicios/fitcron-320.webp'),
  ('Elevación frontal', '/ejercicios/fitcron-323.webp'),
  ('Crunch en polea', '/ejercicios/fitcron-86.webp'),
  ('Elevación de piernas colgado', '/ejercicios/fitcron-72.webp'),
  ('Rueda abdominal', '/ejercicios/fitcron-31.webp'),
  ('Plancha', '/ejercicios/fitcron-65.webp'),
  ('Encogimientos con barra', '/ejercicios/fitcron-382.webp'),
  ('Encogimientos con mancuernas', '/ejercicios/fitcron-349.webp')
) as v(nombre, imagen_url)
where lower(btrim(e.nombre)) = lower(v.nombre)
  and e.imagen_url is null;

-- 5) Resumen -----------------------------------------------------------------
select
  count(*) filter (where origen like 'fitcron-%') as ejercicios_fitcron,
  count(*) filter (where imagen_url is not null) as con_foto,
  count(*) as total_biblioteca
from public.ejercicios;
